[project]
name = "my-fastapi-app"
version = "0.1.0"
description = "FastAPI Full-Featured Web Application"
readme = "README.md"
authors = [
    { name = "RAHUL KP KURUP", email = "rahulkpkurup@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.142.2",
]

[tool.uv]
package = false